[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node test-server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000"
